composite -geometry +434+56 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition1.bmp
composite -geometry +720+93 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition2.bmp
composite -geometry +77+41 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition3.bmp
composite -geometry +190+19 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition4.bmp
composite -geometry +495+263 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition5.bmp
composite -geometry +279+1 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition6.bmp
composite -geometry +201+301 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition7.bmp
composite -geometry +618+79 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition8.bmp
composite -geometry +574+33 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition9.bmp
composite -geometry +137+295 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition10.bmp
composite -geometry +91+268 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition11.bmp
composite -geometry +260+43 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition12.bmp
composite -geometry +849+249 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition13.bmp
composite -geometry +68+97 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition14.bmp
composite -geometry +284+23 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition15.bmp
composite -geometry +362+54 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition16.bmp
composite -geometry +180+98 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition17.bmp
composite -geometry +519+74 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition18.bmp
composite -geometry +197+282 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition19.bmp
composite -geometry +220+214 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition20.bmp
composite -geometry +477+238 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition21.bmp
composite -geometry +37+279 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition22.bmp
composite -geometry +323+273 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition23.bmp
composite -geometry +425+152 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition24.bmp
composite -geometry +142+294 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition25.bmp
composite -geometry +173+15 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition26.bmp
composite -geometry +358+212 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition27.bmp
composite -geometry +376+269 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition28.bmp
composite -geometry +625+291 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition29.bmp
composite -geometry +8+28 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition30.bmp
composite -geometry +546+258 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition31.bmp
composite -geometry +275+203 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition32.bmp
composite -geometry +618+166 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition33.bmp
composite -geometry +753+95 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition34.bmp
composite -geometry +103+171 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition35.bmp
composite -geometry +404+60 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition36.bmp
composite -geometry +296+304 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition37.bmp
composite -geometry +783+101 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition38.bmp
composite -geometry +475+215 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition39.bmp
composite -geometry +386+277 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition40.bmp
composite -geometry +510+292 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition41.bmp
composite -geometry +321+288 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition42.bmp
composite -geometry +218+53 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition43.bmp
composite -geometry +677+125 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition44.bmp
composite -geometry +719+79 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition45.bmp
composite -geometry +200+46 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition46.bmp
composite -geometry +431+58 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition47.bmp
composite -geometry +638+51 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition48.bmp
composite -geometry +614+148 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition49.bmp
composite -geometry +208+45 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition50.bmp
composite -geometry +9+7 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition51.bmp
composite -geometry +528+7 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition52.bmp
composite -geometry +129+86 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition53.bmp
composite -geometry +844+86 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition54.bmp
composite -geometry +775+24 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition55.bmp
composite -geometry +413+178 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition56.bmp
composite -geometry +536+273 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition57.bmp
composite -geometry +558+287 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition58.bmp
composite -geometry +283+77 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition59.bmp
composite -geometry +834+297 Target.png Background/Background_frogs.png BMP3:Stimuli/TargetPosition60.bmp
