(1, 'L', 'Cerebellum-vermis', None, 'Scan2', None)
(1, 'L', 'Cingulate-posterior', None, None, 'Scan3')
(1, 'L', 'PostCG-dorsolateral', None, None, 'Scan3')
(1, 'L', 'PreCG-dorsolateral', None, 'Scan2', 'Scan3')
(1, 'L', 'SFG-dorsal/paracingulate', None, 'Scan2', None)
(1, 'L', 'STG', 'Scan1', 'Scan2', 'Scan3')
(1, 'L', 'Thalamus', None, 'Scan2', None)
(1, 'R', 'Cerebellum-VI', None, 'Scan2', 'Scan3')
(1, 'R', 'Cingulate-posterior', None, None, 'Scan3')
(1, 'R', 'IFG-pars opercularis', None, None, 'Scan3')
(1, 'R', 'IFG-pars triangularis', None, None, 'Scan3')
(1, 'R', 'Lingual Gyrus', None, None, 'Scan3')
(1, 'R', 'LOC', None, 'Scan2', None)
(1, 'R', 'MTG', 'Scan1', 'Scan2', None)
(1, 'R', 'SFG-dorsal/paracingulate', None, 'Scan2', None)
(1, 'R', 'STG', None, None, 'Scan3')
(1, 'R', 'Thalamus', None, 'Scan2', 'Scan3')
(2, 'L', 'LOC-inferior', None, 'Scan2', 'Scan3')
(2, 'L', 'MTG-anterior', 'Scan1', None, None)
(2, 'L', 'MTG-posterior', 'Scan1', None, None)
(2, 'L', 'Precuneus-inferior', None, None, 'Scan3')
(2, 'L', 'Precuneus-superior', 'Scan1', None, None)
(2, 'L', 'SMG', None, None, 'Scan3')
(2, 'L', 'SMG', None, 'Scan2', None)
(2, 'L', 'Subcallosal gray', None, None, 'Scan3')
(2, 'R', 'Angular Gyrus', None, 'Scan2', None)
(2, 'R', 'Caudate-head', 'Scan1', None, None)
(2, 'R', 'Caudate-head', 'Scan1', None, None)
(2, 'R', 'Cingulate-anterior', None, None, 'Scan3')
(2, 'R', 'Insula-anterior', None, None, 'Scan3')
(2, 'R', 'Insula-middle', None, None, 'Scan3')
(2, 'R', 'LOC-dorsolateral', None, 'Scan2', None)
(2, 'R', 'LOC-inferior', 'Scan1', None, None)
(2, 'R', 'MTG-anterior', 'Scan1', None, None)
(2, 'R', 'MTG-posterior', 'Scan1', None, None)
(2, 'R', 'PreCG-lateral', 'Scan1', 'Scan2', None)
(2, 'R', 'Precuneus-inferior', 'Scan1', None, 'Scan3')
(2, 'R', 'STG-posterior', None, None, 'Scan3')
(3, 'L', 'Angular Gyrus', 'Scan1', 'Scan2', 'Scan3')
(3, 'L', 'Anterior Insula', None, None, 'Scan3')
(3, 'L', 'Brainstem-midbrain', None, None, 'Scan3')
(3, 'L', 'IFG-pars opercularis', 'Scan1', 'Scan2', None)
(3, 'L', 'MFG--anterior', None, 'Scan2', None)
(3, 'L', 'MFG-dorsolateral', None, None, 'Scan3')
(3, 'L', 'MFG-ventral', None, None, 'Scan3')
(3, 'L', 'MTG', 'Scan1', 'Scan2', 'Scan3')
(3, 'L', 'MTG-posterior', None, 'Scan2', None)
(3, 'L', 'Orbital Gyrus', None, 'Scan2', None)
(3, 'L', 'PreCG-Inferior', None, 'Scan2', None)
(3, 'L', 'Precuneus-superior', 'Scan1', None, 'Scan3')
(3, 'L', 'SFG-dorsomedial', 'Scan1', None, 'Scan3')
(3, 'L', 'SFG-frontal pole', None, None, 'Scan3')
(3, 'L', 'SFG-ventromedial', None, None, 'Scan3')
(3, 'L', 'SMG-inferior', None, 'Scan2', None)
(3, 'L', 'Thalamus', None, 'Scan2', 'Scan3')
(3, 'R', 'Brainstem-midbrain', None, None, 'Scan3')
(3, 'R', 'Cingulate-posterior inferior', None, None, 'Scan3')
(3, 'R', 'Fusiform-occipital division', None, 'Scan2', None)
(3, 'R', 'IFG-pars opercularis', 'Scan1', None, None)
(3, 'R', 'IFG-pars orbitalis', None, 'Scan2', 'Scan3')
(3, 'R', 'Insula-anterior', None, None, 'Scan3')
(3, 'R', 'Insula-middle', 'Scan1', 'Scan2', None)
(3, 'R', 'Lingual Gyrus', None, 'Scan2', None)
(3, 'R', 'LOC-dorsolateral', None, None, 'Scan3')
(3, 'R', 'LOC-superior', 'Scan1', None, 'Scan3')
(3, 'R', 'Precuneus-inferior', None, None, 'Scan3')
(3, 'R', 'SFG-dorsomedial', 'Scan1', 'Scan2', 'Scan3')
(3, 'R', 'SFG-ventromedial', None, 'Scan2', 'Scan3')
(3, 'R', 'STG-temporal pole', None, 'Scan2', None)
(3, 'R', 'Thalamus', None, None, 'Scan3')
(4, 'L', 'Amygdala', None, None, 'Scan3')
(4, 'L', 'Angular Gyrus', 'Scan1', None, 'Scan3')
(4, 'L', 'Brainstem-midbrain', 'Scan1', None, None)
(4, 'L', 'Cerebellum-V', 'Scan1', None, None)
(4, 'L', 'Cingulate-anterior', None, 'Scan2', None)
(4, 'L', 'Cingulate-posterior', None, None, 'Scan3')
(4, 'L', 'Fusiform-temporal division', 'Scan1', None, None)
(4, 'L', 'Globus Palidus', None, None, 'Scan3')
(4, 'L', 'IFG-pars opercularis', 'Scan1', 'Scan2', None)
(4, 'L', 'IFG-pars orbitalis', None, None, 'Scan3')
(4, 'L', 'MFG-dorsolateral', None, 'Scan2', None)
(4, 'L', 'MFG-frontal pole', 'Scan1', None, None)
(4, 'L', 'MTG', 'Scan1', 'Scan2', 'Scan3')
(4, 'L', 'Orbital gyrus', 'Scan1', 'Scan2', 'Scan3')
(4, 'L', 'Parahippocampal gyrus', 'Scan1', None, None)
(4, 'L', 'Parahippocampal gyrus', None, None, 'Scan3')
(4, 'L', 'Precuneus-inferior', None, 'Scan2', None)
(4, 'L', 'Precuneus-middle', 'Scan1', None, None)
(4, 'L', 'Putamen', 'Scan1', None, None)
(4, 'L', 'SFG-dorsomedial', 'Scan1', None, None)
(4, 'L', 'SFG-dorsomedial', None, 'Scan2', None)
(4, 'L', 'SFG-dosolateral', None, None, 'Scan3')
(4, 'L', 'SFG-frontal pole', 'Scan1', None, 'Scan3')
(4, 'L', 'Thalamus', 'Scan1', None, None)
(4, 'R', 'Angular Gyrus', 'Scan1', 'Scan2', 'Scan3')
(4, 'R', 'cerebellum-Crus II', None, None, 'Scan3')
(4, 'R', 'Cerebellum-V', None, 'Scan2', None)
(4, 'R', 'Cerebellum-Vermis', 'Scan1', None, None)
(4, 'R', 'Cerebellum-VI', 'Scan1', None, None)
(4, 'R', 'Cingulate-anterior', None, 'Scan2', None)
(4, 'R', 'Lingual Gyrus', 'Scan1', None, 'Scan3')
(4, 'R', 'Lingual/Cerebellum', 'Scan1', 'Scan2', 'Scan3')
(4, 'R', 'MTG', None, None, 'Scan3')
(4, 'R', 'Parietal operculum', 'Scan1', 'Scan2', 'Scan3')
(4, 'R', 'PostCG-dorsal', 'Scan1', 'Scan2', 'Scan3')
(4, 'R', 'PreCG-dorsal', None, 'Scan2', None)
(4, 'R', 'Precuneus-inferior', 'Scan1', None, None)
(4, 'R', 'SFG-dorsomedial', 'Scan1', 'Scan2', 'Scan3')
(4, 'R', 'SFG-ventromedial', None, None, 'Scan3')
(4, 'R', 'STG', 'Scan1', 'Scan2', None)
(5, 'L', 'Cerebellum-crus I', None, 'Scan2', None)
(5, 'L', 'Cingulate-anterior', 'Scan1', 'Scan2', 'Scan3')
(5, 'L', 'Cingulate-posterior', 'Scan1', 'Scan2', 'Scan3')
(5, 'L', 'Cingulate-posterior inferior', None, None, 'Scan3')
(5, 'L', 'Cuneate gyrus', None, 'Scan2', 'Scan3')
(5, 'L', 'Fusiform-Temporal division', None, None, 'Scan3')
(5, 'L', 'ITG-posterior', 'Scan1', 'Scan2', None)
(5, 'L', 'LOC-superior', None, 'Scan2', 'Scan3')
(5, 'L', 'MFG-dorsolateral', None, None, 'Scan3')
(5, 'L', 'PreCG-dorsolateral', 'Scan1', 'Scan2', 'Scan3')
(5, 'L', 'SFG--ventromedial', 'Scan1', None, None)
(5, 'L', 'SFG-frontal pole', None, 'Scan2', 'Scan3')
(5, 'L', 'SMG', 'Scan1', None, None)
(5, 'L', 'SPL', None, 'Scan2', None)
(5, 'R', 'Angular Gyrus', None, None, 'Scan3')
(5, 'R', 'Cerebellum-crus I', 'Scan1', None, None)
(5, 'R', 'Cingulate-anterior', None, None, 'Scan3')
(5, 'R', 'Cingulate-posterior', 'Scan1', None, None)
(5, 'R', 'Cingulate-posterior inferior', None, 'Scan2', None)
(5, 'R', 'Cuneate gyrus', None, 'Scan2', 'Scan3')
(5, 'R', 'IFG-pars opercularis', None, None, 'Scan3')
(5, 'R', 'IFG-pars triangularis', 'Scan1', 'Scan2', None)
(5, 'R', 'ITG', 'Scan1', 'Scan2', 'Scan3')
(5, 'R', 'LOC-superior', 'Scan1', 'Scan2', None)
(5, 'R', 'SFG-frontal pole', 'Scan1', 'Scan2', 'Scan3')
(5, 'R', 'SMG', 'Scan1', 'Scan2', None)
(5, 'R', 'STG-temporal pole', None, 'Scan2', 'Scan3')
