"""
==============================================================================
Program name: examine.py
      Author: Kyle Reese Almryde
        Date: 11/02/12 @ 04:39 PM

Purpose: This program examines the reports generated by afni's 3dInfo and
         determines what the most consistent datatype is, and other formatting
         info so that we can make a decision on preprocessing for the IceWord
         data
==============================================================================
"""


def orientCodeHandler(orient, runNum, fout):
    header = 'Scan ' + runNum + ' Image Orientation:\n========================\n'
    orientCode = {'RAI': 0, 'RAS': 0, 'RPI': 0, 'RPS': 0, 'LAI': 0, 'LAS': 0, 'LPI': 0, 'LPS': 0}
    fout.write(header)

    for el in orient:
        if el in orientCode:
            orientCode[el] += 1
    # Write the orient code and their counts if great than 0 to file
    for key in orientCode:
        if key > 0:
            fout.write(key + ': ' + str(orientCode[key]) + '\n')


#===============================[Start of Main]===============================

def main():
    runNum = raw_input('Enter Run#: ')
    fin = open('Report_Run#.txt')
    fout = open('Report_Results_allRuns.txt', 'a+')
    lines = fin.readlines()
    size = len(lines)

    orient = []

    for i in range(size):
        if lines[i].split(':')[0] == 'Data Axes Orientation':
            orient.append(lines[i + 6][3].split()[5][0:3])   # This will provide the orient code

        orientCodeHandler(orient)

if __name__ == '__main__':
    main()
