#!/usr/bin/env tcsh
echo "Follow this command line format: ./AnovaGam"
# --------------------------------------------------
# Script Setup
set images_home = /Volumes/Data/MRI-AttnMem/Anova/
#set type = Group/Female/Male

foreach value (1 2 3 4 5 6 7)

# --------------------------------------------------
3dcalc -a FF/mean_GAM${value}_ff+tlrc -b MF/mean_GAM${value}_mf+tlrc -c NF/mean_GAM${value}_nf+tlrc -expr '(a+b+c)' -prefix Combined/mean_GAM${value}_ff-mf-nf+tlrc
end
