#!/usr/bin/env tcsh
# --------------------------------------------------
# The purpose of this script is to threshold to a p = 0.05 at a corrected voxel 1640
echo "Follow this command line format: ./Threshold"
foreach g (1 2 3 4 5 6 7) #gam
set H = /Volumes/Data/MRI-AttnMem/Anova #Home
set C = $H/Contrasts #Contrasts
set A = $H/Anova_GAM${g}_results #Anova
# foreach mask (AI CAU CER CIN IFG IFG2 IFG3 MFG MFG2 MTG SFG SMG SOG STG THA)
# --------------------------------------------------
# Perform 3dmerge on mean conditions
# echo "mean_GAM${g}_${t}_0.05"
# 3dmerge -1noneg -dxyz=1 -1clust 1 -1640 -1thresh 2.160 -prefix ${t}/mean_GAM${g}_${t}_0.05 $A/mean_GAM${g}_${t}+tlrc
# --------------------------------------------------
#Preform 3dmerge on base-line subtracted conditions
#echo "base_${g}_${t}_0.05"
#3dmerge -1noneg -dxyz=1 -1clust 1 -1640 -1thresh 2.160 -prefix ${t}/base_GAM${g}_${t}_0.05 $A/base_GAM${g}_${t}+tlrc
# # --------------------------------------------------
foreach v (FvM FvN FvMN MvF MvN  MvFN NvF NvM NvFM) #variation
# # Preform 3dmerge on contrast conditions
# echo "contr_GAM${g}_${v}_0.05+tlrc"
3dmerge -dxyz=1 -1clust 1 -1640 -1thresh 2.160 -prefix ${C}/contr_GAM${g}_${v}_0.05+tlrc $A/contr_GAM${g}_${v}+tlrc
# # --------------------------------------------------
#end
end
end
