#!/bin/sh
#This script was written by Kyle Almryde, University of Arizona, 6/19/2011
# --------------------------------------------------
# Script setup

echo "${STROOP}"

mkdir ${STROOP}/ICA

while read subj
do
	for run in voice word
	do

	base=${STROOP}/${subj}/run2_${run} results=${STROOP}/ICA func=${subj}_${run}

		3dTcat -prefix ${base}/${func}_tcat ${base}/${func}_epan+orig'[4..$]'
		3dAFNItoNIFTI ${base}/${func}_tcat+orig ${results}/${func}.nii

	done; done < ${STROOP}/Utilities/subjls.txt