#!/bin/sh
# define path variables that can be called by my scripts
source /usr/local/ref/img_profile

#Defined: IJN=/Exps/Data/IJN
# This is the subject directory
SUBJECTDIR=`pwd`
SUBJECT=`basename $SUBJECTDIR`

export REG=${SUBJECTDIR}/Reg
export FUNC=${SUBJECTDIR}/func
export ANAT=${SUBJECTDIR}/anat
export ORIG=${SUBJECTDIR}/Orig
export REGTEST=${SUBJECTDIR}/Reg_Test
export SUBROIS=${SUBJECTDIR}/SubjectROIs
export PICS=${SUBJECTDIR}/Pictures
export STATS=${SUBJECTDIR}/Access



