#!/bin/sh
# define path variables that can be called by my scripts
source /usr/local/ref/img_profile

# This is the subject directory
SUBJECTDIR=`pwd`
SUBJECT=`basename $SUBJECTDIR`
# remove the initial e from the name
LOGPREFIX=`echo $SUBJECT| sed -e 's/e//'`

export DTI=${SUBJECTDIR}/DTI
export BEDPOST=${DTI}/Bed.bedpostX
export XFMS=${BEDPOST}/xfms
export REG=${BEDPOST}/xfms

export MORPH=${SUBJECTDIR}/Morph
export CC=${MORPH}/CC
export WMH=${MORPH}/WMH
export HIPPO=${MORPH}/HIPPO

export ORIG=${SUBJECTDIR}/Orig
export REGTEST=${SUBJECTDIR}/Reg_Test
export SUBROIS=${SUBJECTDIR}/SubjectROIs
export PICS=${SUBJECTDIR}/Pictures
export STATS=${SUBJECTDIR}/Access
export FUNC=${SUBJECTDIR}/Func
export EPRIME=${FUNC}/Eprime
