cd S19/S19_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S20/S20_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S21/S21_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S22/S22_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S23/S23_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S24/S24_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S24/S24_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S25/S25_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S26/S26_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S27/S27_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S28/S28_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S29/S29_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S30/S30_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S31/S31_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S32/S32_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S33/S33_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S34/S34_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S35/S35_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S36/S36_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S37/S37_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S38/S38_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S39/S39_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S40/S40_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S41/S41_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S42/S42_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S43/S43_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S43/S44_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S45/S45_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S46/S46_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S47/S47_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../
cd S48/S48_voice_results/07_Deconvolve cp *_norm_irf+tlrc* ../../../ROIs cd ../