#!/bin/sh

#paths
source /usr/local/ref/img_profile

if [ $# -lt 1 ]
then
    echo "Usage: $0 <image_stem>"
    echo "Example: $0  Aud"
    echo "Finds all files in current dir with Aud in the name.  Binarizes these and makes the hotspot"
    echo ""  
    exit 1
fi

filename=${1}
echo "$filename"
# Make the directory Binaries if it does not already exist
if [ ! -d Binaries ]; then
    mkdir Binaries
fi

if [ ! -d Hotspot ]; then
    mkdir Hotspot
fi

for img in *${filename}*.nii.gz; do 
    image=`basename -s .nii.gz ${img}`
    # check to see if the hotspot_template exists, if not, create it.
    if [ ! -e Hotspot/hotspot_${filename} ]; then
        fmask ${img} Hotspot/hotspot_${filename} 
    fi
    echo ${image}
    # Make binary images of the appropriate files
    fslmaths ${image} -bin Binaries/${image}_bin
    # Make the hotspot image
    fslmaths Binaries/${image}_bin -add Hotspot/hotspot_${filename} Hotspot/hotspot_${filename}
done
