comp = [4, 2, 4, 3, 4, 5, 3, 4, 3, 3, 2, 2, 5, 5, 4, 4, 4,
        1, 4, 1, 4, 5, 2, 4, 4, 5, 1, 1, 5, 4, 5, 3, 5, 5,
        5, 5, 3, 4, 5, 4, 1, 3, 4, 3, 5, 3, 4, 1, 5, 2, 3,
        2, 3, 5, 5, 1, 3, 4, 4, 1, 2, 3, 2, 2, 3, 5, 5, 3,
        3, 4, 5, 4, 3, 1, 3, 4, 4, 2, 2, 2, 3, 2, 3, 4, 4,
        4, 4, 4, 1, 4, 1, 5, 3, 2, 2, 2, 3, 4, 4, 4, 2, 3,
        4, 5, 1, 1, 3, 4, 4, 3, 4, 4, 3, 4, 5, 5, 3, 3, 4,
        5, 2, 2, 5, 3, 5, 1, 1, 4, 2, 3, 5, 2, 1, 1, 3, 3, 4]

hemi = ['L', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'L', 'R', 'R', 'R', 'L', 'R',
        'R', 'L', 'R', 'L', 'R', 'R', 'R', 'L', 'R', 'L', 'R', 'R', 'L', 'R',
        'L', 'L', 'R', 'R', 'L', 'R', 'L', 'R', 'R', 'L', 'L', 'L', 'R', 'L',
        'L', 'R', 'R', 'R', 'L', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'L', 'R', 'R', 'L', 'R', 'L', 'L', 'L',
        'L', 'L', 'L', 'R', 'L', 'L', 'R', 'L', 'R', 'L', 'L', 'R', 'L', 'L',
        'L', 'L', 'R', 'R', 'L', 'R', 'L', 'L', 'L', 'R', 'L', 'R', 'R', 'L',
        'R', 'L', 'L', 'L', 'L', 'L', 'L', 'R', 'L', 'L', 'L', 'R', 'R', 'L',
        'L', 'L', 'L', 'R', 'L', 'R', 'R', 'L', 'L', 'L', 'R', 'L', 'L', 'R',
        'L', 'R', 'R', 'R', 'R', 'L', 'L', 'R', 'L', 'R', 'L']

rois = ['Amygdala', 'Angular Gyrus', 'Angular Gyrus',
        'Angular Gyrus', 'Angular Gyrus', 'Angular Gyrus',
        'Anterior Insula', 'Brainstem-midbrain', 'Brainstem-midbrain',
        'Brainstem-midbrain', 'Caudate-head', 'Caudate-head',
        'Cerebellum-crus I', 'Cerebellum-crus I', 'cerebellum-Crus II',
        'Cerebellum-V', 'Cerebellum-V', 'Cerebellum-vermis',
        'Cerebellum-Vermis', 'Cerebellum-VI', 'Cerebellum-VI',
        'Cingulate-anterior', 'Cingulate-anterior', 'Cingulate-anterior',
        'Cingulate-anterior', 'Cingulate-anterior', 'Cingulate-posterior',
        'Cingulate-posterior', 'Cingulate-posterior', 'Cingulate-posterior',
        'Cingulate-posterior', 'Cingulate-posterior inferior',
        'Cingulate-posterior inferior', 'Cingulate-posterior inferior',
        'Cuneate gyrus', 'Cuneate gyrus', 'Fusiform-occipital division',
        'Fusiform-temporal division', 'Fusiform-Temporal division',
        'Globus Palidus', 'IFG-pars opercularis', 'IFG-pars opercularis',
        'IFG-pars opercularis', 'IFG-pars opercularis', 'IFG-pars opercularis',
        'IFG-pars orbitalis', 'IFG-pars orbitalis', 'IFG-pars triangularis',
        'IFG-pars triangularis', 'Insula-anterior', 'Insula-anterior',
        'Insula-middle', 'Insula-middle', 'ITG', 'ITG-posterior',
        'Lingual Gyrus', 'Lingual Gyrus', 'Lingual Gyrus',
        'Lingual/Cerebellum', 'LOC', 'LOC-dorsolateral', 'LOC-dorsolateral',
        'LOC-inferior', 'LOC-inferior', 'LOC-superior', 'LOC-superior',
        'LOC-superior', 'MFG--anterior', 'MFG-dorsolateral',
        'MFG-dorsolateral', 'MFG-dorsolateral', 'MFG-frontal pole',
        'MFG-ventral', 'MTG', 'MTG', 'MTG', 'MTG', 'MTG- anterior',
        'MTG-anterior', 'MTG-posterior', 'MTG-posterior', 'MTG-posterior',
        'Orbital Gyrus', 'Orbital gyrus', 'Parahippocampal gyrus',
        'Parahippocampal gyrus', 'Parietal operculum', 'PostCG-dorsal',
        'PostCG-dorsolateral', 'PreCG-dorsal', 'PreCG-dorsolateral',
        'PreCG-dorsolateral', 'PreCG-Inferior', 'PreCG-lateral',
        'Precuneus-inferior', 'Precuneus-inferior', 'Precuneus-inferior',
        'Precuneus-inferior', 'Precuneus-inferior', 'Precuneus-middle',
        'Precuneus-superior', 'Precuneus-superior', 'Putamen',
        'SFG-ventromedial', 'SFG-dorsal/paracingulate',
        'SFG-dorsal/paracingulate', 'SFG-dorsomedial', 'SFG-dorsomedial',
        'SFG-dorsomedial', 'SFG-dorsomedial', 'SFG-dorsomedial',
        'SFG-dosolateral', 'SFG-frontal pole', 'SFG-frontal pole',
        'SFG-frontal pole', 'SFG-frontal pole', 'SFG-ventromedial',
        'SFG-ventromedial', 'SFG-ventromedial', 'SMG', 'SMG', 'SMG', 'SMG',
        'SMG-inferior', 'SPL', 'STG', 'STG', 'STG', 'STG-posterior',
        'STG-temporal pole', 'STG-temporal pole', 'Subcallosal gray',
        'Thalamus', 'Thalamus', 'Thalamus', 'Thalamus', 'Thalamus']
