####################################################################################################
. $PROFILE/${1}_profile.sh
####################################################################################################
cd ${BEHAV_dir}
###################################################################################################
# Written by Kyle Almryde 1/21/2012
# Thanks to Tom Hicks and Dianne Patterson for suggestions and troubleshooting.
# Buttons 1 and 2 are equivalent (and what the subject should press if s/he thinks the test is a 
# nonword). Buttons 3 and 4 are equivalent (and what the subject should press if s/he thinks the 
# test is a true word)
####################################################################################################
echo "-------------------------------- eprime.sh ----------------------------------"
echo "This massages text from an eprime file generated by the ${1} imaging experiment"
echo "-------------------------------- ${subrun} --------------------------------"
echo ""
####################################################################################################
# The eprime on the new scanner PC produces text files in UTF16.  This breaks everything. iconv can 
# do the conversion back to a standard text format that sed likes.
####################################################################################################

#iconv -f UTF-16 -t ISO-8859-1 ${subj}-${run}.txt > iconv.iso.${subrun}.txt
####################################################################################################
# This is crucial, as the windows line returns broke paste in horrible ways
# The dos2unix tool is part of the fink distribution, but you have to go get it.
# Thanks Tom ; )
####################################################################################################

#dos2unix iconv.iso.${subrun}.txt
####################################################################################################
# To make sure we never encounter this horrible problem ever again, we are going to replace the
# Original file all together, and mv the iconv.iso.file-name to the original name (so none are the
# wiser ;-)
####################################################################################################

#rm ${subj}-${run}.txt; mv iconv.iso.${subrun}.txt ${subj}-${run}.txt
####################################################################################################
# Extract just the rows of interest. By using the -e the sed commands are all executed together,
# so we retain the line ordering of the file
####################################################################################################

cat ${subj}-${run}.txt | sed -n -e '/SoundFile:/p' -e '/WordType:/p' -e '/SpeakerGender:/p' -e \
	'/SlideTarget.RT:/p' -e '/SlideTarget.RESP:/p' -e '/SlideTarget.CRESP:/p' -e \
	'/SlideTarget.OnsetTime:/p' | tr -d '\t' > temp.${subrun}
####################################################################################################
# Create the Report file and echo the column title into it. Run3 does not have a SpeakerGender
# component, so do not add that column for that run
####################################################################################################

if [ "${run}" = "TP1" ]; then
	echo "Timing SoundFile WordType OnsetTime RT RESP CRESP ACC" > temp.report.${subrun}
else
	echo "Timing SoundFile WordType SpeakerGender OnsetTime RT RESP CRESP ACC" > temp.report.${subrun}
fi
####################################################################################################
# Add a clean list of the sound files, swap _ for spaces in wav file names
####################################################################################################

cat temp.${subrun} | sed -n 's/SoundFile: //p' | sed 's/.wav//g' > soundfile.${subrun}
####################################################################################################
# Get lines containing RT (or Target.RESP or CRESP) and save the 2nd field
####################################################################################################

cat temp.${subrun} | grep WordType | awk '{print $2}' >> wrd.${subrun}
cat temp.${subrun} | grep SlideTarget.OnsetTime | awk '{print $2}' >> onset.${subrun}
cat temp.${subrun} | grep RT | awk '{print $2}' >> rt.${subrun}
cat temp.${subrun} | grep SlideTarget.RESP | awk '{print $2}' >> resp.${subrun}
cat temp.${subrun} | grep SlideTarget.CRESP | awk '{print $2}' >> cresp.${subrun}
cat temp.${subrun} | grep SpeakerGender | awk '{print $2}' >> speakergender.${subrun}
####################################################################################################
# For 
####################################################################################################

if [ "${run}" = "TP1" ]; then
	cat wrd.${subrun} | sed -e "s/N/New/g" -e "s/null/NULL/g" -e "s/O/Old/g" >> wordtype.${subrun}
else 
	cat wrd.${subrun} | sed -e "s/null/NULL/g" -e "s/A/Animal/g" -e "s/F/Food/g" \
		>> wordtype.${subrun}
fi
####################################################################################################
# Paste the fields I want in contiguous space separated columns
####################################################################################################

if [ "${run}" = "TP1" ]; then
	paste -d" " etc/timing.txt soundfile.${subrun} wordtype.${subrun} onset.${subrun} rt.${subrun} \
		resp.${subrun} cresp.${subrun} >> temp.report.${subrun}
else
	paste -d" " etc/timing.txt soundfile.${subrun} wordtype.${subrun} speakergender.${subrun} \
		onset.${subrun} rt.${subrun} resp.${subrun} cresp.${subrun} >> temp.report.${subrun}
fi	
###################################################################################################
# Change the delimiter from spaces to tabs
###################################################################################################

cat temp.report.${subrun} | awk -v OFS='\t' '$1=$1' >> Report.${subrun}.txt
####################################################################################################
# Remove the temporary files used to construct the final report, and move the original files
# to the etc directory
####################################################################################################

rm resp.${subrun} rt.${subrun} temp.${subrun} speakergender.${subrun} wrd.${subrun} \
	wordtype.${subrun} cresp.${subrun} temp.report.${subrun} onset.${subrun} soundfile.${subrun}

mv ${subj}-${run}.txt etc/
####################################################################################################


