################################################################################
. $PROFILE/${1}_profile.sh
################################################################################
cd ${BEHAV_dir}
################################################################################
echo "-------------------------------- Examination ----------------------------------"
echo "This examines the results from text originating in an eprime file generated by "
echo "the ${1} imaging experiment. It will match resposes, average results, then link"
echo "various items from the Test-Phase to the corresponding Study-Phase"
echo "-------------------------------- ${subrun} --------------------------------"
echo ""
################################################################################
# This section will create the ACC.Report
#
#  First: Using Paste, combine the resp.file and the cresp.file, creating the 
#		  resp.cresp.file. 
# Second: Compare the contents of field $1 to $3, if they are equal, print a 
#		  value of 1 in field $3 if they are different, print a value of 0 in 
#		  filed $3, name the file acc.file
################################################################################

#if [ "${run}" = "SP1" ]; then

#	echo "WordType SpeakerGender RESP CRESP ACC" >> acc.header.${subrun}
#	paste -d" " wordtype.${subrun} wordtype.${subrun} resp.${subrun} cresp.${subrun} acc.${subrun} >> tmp.acc.header.${subrun}
#	grep -E 'Animal|Food' tmp.acc.header.${subrun} >> acc.header.${subrun}

#elif [ "${run}" = "TP1" ]; then

#	echo "WordType RESP CRESP ACC" >> acc.header.${subrun}
#	paste -d" " wordtype.${subrun} resp.${subrun} cresp.${subrun} acc.${subrun} >> tmp.acc.header.${subrun}
#	grep -E 'Old|New' tmp.acc.header.${subrun} >> acc.header.${subrun}

#else
#	echo "SpeakerGender RESP CRESP ACC" >> acc.header.${subrun}
#	paste -d" " speakergender.${subrun} resp.${subrun} cresp.${subrun} acc.${subrun} >> tmp.acc.header.${subrun}
#	grep male tmp.acc.header.${subrun} >> acc.header.${subrun}
#fi
#	cat acc.header.${subrun} | awk -v OFS='\t' '$1=$1' >> ACC.Report.${subrun}.txt

################################################################################
# Read the 4th column, denoting accuracy, caluclate the mean Accuracy, then create a file listing
# the Subject_Run = Mean score for the entire population name it ${cond}_Summary_%ACC.txt
# Do the same, but count the sum, not the mean.
################################################################################

#echo ""; echo "creating ACC Summary files"
#<${subcond}.ACC.txt awk '{sum+=$4} END { print sum/NR*100"%"}' >> ${results_dir}/${runcond}_Summary_ACC%.txt
#<${subcond}.ACC.txt awk '{sum+=$4} END { print sum}' >> ${results_dir}/${runcond}_Summary_ACC.txt
################################################################################
# Pass the contents of Report.${subrun}.txt to awk
################################################################################
#cat Report.${subrun}.txt | 
# d' = z(HITS) - z(FAlarms) 

# Things to remember!!
#sub=$1		run=$2	target=$3	time=$4	  grp=$5	rt=$6 	RESP=$7 acc=$8





if [ "${run}" = "SP1" ]; then
	cat Reports/Report.${subrun}.txt | grep -E "Af.*[1]$|Am.*[1]$" | awk '{print $3}' >> ${subrun}.Animal.mf.hits
	cat Reports/Report.${subrun}.txt | grep -E "Ff.*[1]$|Fm.*[1]$" | awk '{print $3}' >> ${subrun}.Food.mf.hits
	cat Reports/Report.${subrun}.txt | grep -E "Af.*[0]$|Am.*[0]$" | awk '{print $3}' >> ${subrun}.Animal.mf.miss
	cat Reports/Report.${subrun}.txt | grep -E "Ff.*[0]$|Fm.*[0]$" | awk '{print $3}' >> ${subrun}.Food.mf.miss


elif [ "${run}" = "SP2" ]; then # 1 2 3 4 5 6 7 8 9 0 11 12 13 14 15 16
	cat Reports/Report.${subrun}.txt | grep -E "aF.*[1]$|fF.*[1]$"| awk '{print $3}' >> ${subrun}.af.Female.hits
	cat Reports/Report.${subrun}.txt | grep -E "aM.*[1]$|fM.*[1]$"| awk '{print $3}' >> ${subrun}.af.Male.hits
	cat Reports/Report.${subrun}.txt | grep -E "aF.*[0]$|fF.*[0]$"| awk '{print $3}' >> ${subrun}.af.Female.miss	
	cat Reports/Report.${subrun}.txt | grep -E "aM.*[0]$|fM.*[0]$"| awk '{print $3}' >> ${subrun}.af.Male.miss

elif [ "${run}" = "TP1" ]; then			
	cat Reports/Report.${subrun}.txt | grep "O.*[1]$" | awk '{print $3}' >> ${subrun}.old.hits
	cat Reports/Report.${subrun}.txt | grep "O.*[0]$" | awk '{print $3}' >> ${subrun}.old.miss
	cat Reports/Report.${subrun}.txt | grep "N.*[1]$" | awk '{print $3}' >> ${subrun}.new.hits
	cat Reports/Report.${subrun}.txt | grep "N.*[0]$" | awk '{print $3}' >> ${subrun}.new.miss

elif [ "${run}" = "TP2" ]; then
	cat Reports/Report.${subrun}.txt | grep -E "aF.*[1]$|fF.*[1]$"| awk '{print $3}' >> ${subrun}.af.Female.hits
	cat Reports/Report.${subrun}.txt | grep -E "aM.*[1]$|fM.*[1]$"| awk '{print $3}' >> ${subrun}.af.Male.hits	
	cat Reports/Report.${subrun}.txt | grep -E "aF.*[0]$|fF.*[0]$"| awk '{print $3}' >> ${subrun}.af.Female.miss
	cat Reports/Report.${subrun}.txt | grep -E "aM.*[0]$|fM.*[0]$"| awk '{print $3}' >> ${subrun}.af.Male.miss

fi


# Things to remember!!
#sub=$1		run=$2	target=$3	time=$4		grp=$5	rt=$6 	RESP=$7 acc=$8

#cat something.txt >> somethingelse.txt

#NOTE I CHANGED THE print $4 to $6 (time to rt) so marija could get reaction time scores

#SP1 ==> TP1
if [ "${run}" = "SP1" ]; then
	grep -f ${subrun}.Animal.mf.hits Reports/Report.${subj}.TP1.txt | awk '{print $6}' >> tmp.stim.${subj}.TP1.Animal.mf.hits.txt
	grep -f ${subrun}.Food.mf.hits Reports/Report.${subj}.TP1.txt | awk '{print $6}' >> tmp.stim.${subj}.TP1.Food.mf.hits.txt
	grep -f ${subrun}.Food.mf.miss Reports/Report.${subj}.TP1.txt | awk '{print $6}' >> tmp.stim.${subj}.TP1.Food.mf.miss.txt
	grep -f ${subrun}.Animal.mf.miss Reports/Report.${subj}.TP1.txt | awk '{print $6}' >> tmp.stim.${subj}.TP1.Animal.mf.miss.txt
	
	cat tmp.stim.${subj}.TP1.Animal.mf.hits | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP1.Animal.mf.hits.1D
	cat tmp.stim.${subj}.TP1.Food.mf.hits | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP1.Food.mf.hits.1D
	cat tmp.stim.${subj}.TP1.Food.mf.miss | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP1.Food.mf.miss.1D
	cat tmp.stim.${subj}.TP1.Animal.mf.miss | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP1.Animal.mf.miss.1D

#SP2 ==> TP2
elif [ "${run}" = "SP2" ]; then
	
	grep -f ${subrun}.af.Female.hits Reports/Report.${subj}.TP2.txt | awk '{print $6}' >> tmp.stim.${subj}.TP2.af.Female.hits.txt
	grep -f ${subrun}.af.Male.hits Reports/Report.${subj}.TP2.txt | awk '{print $6}' >> tmp.stim.${subj}.TP2.af.Male.hits.txt
	grep -f ${subrun}.af.Male.miss Reports/Report.${subj}.TP2.txt | awk '{print $6}' >> tmp.stim.${subj}.TP2.af.Male.miss.txt
	grep -f ${subrun}.af.Female.miss Reports/Report.${subj}.TP2.txt | awk '{print $6}' >> tmp.stim.${subj}.TP2.af.Female.miss.txt
	
	cat tmp.stim.${subj}.TP2.af.Female.miss | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP2.af.Female.miss.1D
	cat tmp.stim.${subj}.TP2.af.Male.miss | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP2.af.Male.miss.1D
	cat tmp.stim.${subj}.TP2.af.Male.hits | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP2.af.Male.hits.1D
	cat tmp.stim.${subj}.TP2.af.Female.hits | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.TP2.af.Female.hits.1D

#TP1 ==> SP1
elif [ "${run}" = "TP1" ]; then
	
	grep -f ${subrun}.old.hits Reports/Report.${subj}.SP1.txt | awk '{print $6}' >> tmp.stim.${subj}.SP1.old.hits.txt
	grep -f ${subrun}.old.miss Reports/Report.${subj}.SP1.txt | awk '{print $6}' >> tmp.stim.${subj}.SP1.old.miss.txt

	cat tmp.stim.${subj}.SP1.old.hits | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.SP1.old.hits.1D
	cat tmp.stim.${subj}.SP1.old.miss | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.SP1.old.miss.1D

#TP2 ==> SP2
elif [ "${run}" = "TP2" ]; then
	
	grep -f ${subrun}.af.Female.hits Reports/Report.${subj}.SP2.txt | awk '{print $6}' >> tmp.stim.${subj}.SP2.af.Female.hits.txt
	grep -f ${subrun}.af.Male.hits Reports/Report.${subj}.SP2.txt | awk '{print $6}' >> tmp.stim.${subj}.SP2.af.Male.hits.txt
	grep -f ${subrun}.af.Male.miss Reports/Report.${subj}.SP2.txt | awk '{print $6}' >> tmp.stim.${subj}.SP2.af.Male.miss.txt
	grep -f ${subrun}.af.Female.miss Reports/Report.${subj}.SP2.txt | awk '{print $6}' >> tmp.stim.${subj}.SP2.af.Female.miss.txt

	cat tmp.stim.${subj}.SP2.af.Female.hits | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.SP2.af.Female.hits.1D
	cat tmp.stim.${subj}.SP2.af.Male.hits | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.SP2.af.Male.hits.1D
	cat tmp.stim.${subj}.SP2.af.Male.miss | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.SP2.af.Male.miss.1D
	cat tmp.stim.${subj}.SP2.af.Female.miss | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim.${subj}.SP2.af.Female.miss.1D
fi


#mv stim.* Stim/
#rm tmp.*
rm stim.*
rm ${subrun}.*

#cat tmp.stim.${subj}.SP2.af.Female.hits.txt | grep "[0-9].*.\.*" | tr '\n' ' ' >> stim_${subj}_SP2_af_Female_hits.1D



#rm *.hits *.falsealarms *.correctReject *.miss



#cat tmp.stim.TS013.SP1.old.hits.txt | grep "[0-9].*.\.*" | tr '\n' ' '

















