#!/usr/bin/env tcsh
echo "Command line conforms to following: ./ROIspheres Subject# v/w"
echo "./ROIspheres S23 v"
# execute via : tcsh -x S#-run-script |& tee output.S#-run-script

# --------------------------------------------------
# script setup



set images_home = /Volumes/Data/Stroop/ROIs/DataSpheres

echo "Count Down Begins"

if ( $#argv > 0 ) then
    set subj = $argv[1]
else
# specify subject = ${subj}
set subj = $1

endif

echo "Assigning Variables"

#set type = v/w
set type = $2
# --------------------------------------------------

3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_lBA45+tlrc > 01_BA45/${subj}_${type}_fvfw_lBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_lBA45+tlrc > 01_BA45/${subj}_${type}_fvmw_lBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_lBA45+tlrc > 01_BA45/${subj}_${type}_fvnw_lBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_lBA45+tlrc > 01_BA45/${subj}_${type}_mvmw_lBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_lBA45+tlrc > 01_BA45/${subj}_${type}_mvfw_lBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_lBA45+tlrc > 01_BA45/${subj}_${type}_mvnw_lBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_rBA45+tlrc > 01_BA45/${subj}_${type}_fvfw_rBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_rBA45+tlrc > 01_BA45/${subj}_${type}_fvmw_rBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_rBA45+tlrc > 01_BA45/${subj}_${type}_fvnw_rBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_rBA45+tlrc > 01_BA45/${subj}_${type}_mvmw_rBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_rBA45+tlrc > 01_BA45/${subj}_${type}_mvfw_rBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_rBA45+tlrc > 01_BA45/${subj}_${type}_mvnw_rBA45.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_lBA44+tlrc > 02_BA44/${subj}_${type}_fvfw_lBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_lBA44+tlrc > 02_BA44/${subj}_${type}_fvmw_lBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_lBA44+tlrc > 02_BA44/${subj}_${type}_fvnw_lBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_lBA44+tlrc > 02_BA44/${subj}_${type}_mvmw_lBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_lBA44+tlrc > 02_BA44/${subj}_${type}_mvfw_lBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_lBA44+tlrc > 02_BA44/${subj}_${type}_mvnw_lBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_rBA44+tlrc > 02_BA44/${subj}_${type}_fvfw_rBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_rBA44+tlrc > 02_BA44/${subj}_${type}_fvmw_rBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_rBA44+tlrc > 02_BA44/${subj}_${type}_fvnw_rBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_rBA44+tlrc > 02_BA44/${subj}_${type}_mvmw_rBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_rBA44+tlrc > 02_BA44/${subj}_${type}_mvfw_rBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_rBA44+tlrc > 02_BA44/${subj}_${type}_mvnw_rBA44.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_lBA13+tlrc > 03_BA13/${subj}_${type}_fvfw_lBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_lBA13+tlrc > 03_BA13/${subj}_${type}_fvmw_lBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_lBA13+tlrc > 03_BA13/${subj}_${type}_fvnw_lBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_lBA13+tlrc > 03_BA13/${subj}_${type}_mvmw_lBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_lBA13+tlrc > 03_BA13/${subj}_${type}_mvfw_lBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_lBA13+tlrc > 03_BA13/${subj}_${type}_mvnw_lBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_rBA13+tlrc > 03_BA13/${subj}_${type}_fvfw_rBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_rBA13+tlrc > 03_BA13/${subj}_${type}_fvmw_rBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_rBA13+tlrc > 03_BA13/${subj}_${type}_fvnw_rBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_rBA13+tlrc > 03_BA13/${subj}_${type}_mvmw_rBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_rBA13+tlrc > 03_BA13/${subj}_${type}_mvfw_rBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_rBA13+tlrc > 03_BA13/${subj}_${type}_mvnw_rBA13.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_dACC+tlrc > 04_dACC/${subj}_${type}_fvfw_dACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_dACC+tlrc > 04_dACC/${subj}_${type}_fvmw_dACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_dACC+tlrc > 04_dACC/${subj}_${type}_fvnw_dACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_dACC+tlrc > 04_dACC/${subj}_${type}_mvmw_dACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_dACC+tlrc > 04_dACC/${subj}_${type}_mvfw_dACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_dACC+tlrc > 04_dACC/${subj}_${type}_mvnw_dACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_vACC+tlrc > 05_vACC/${subj}_${type}_fvfw_vACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_vACC+tlrc > 05_vACC/${subj}_${type}_fvmw_vACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_vACC+tlrc > 05_vACC/${subj}_${type}_fvnw_vACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_vACC+tlrc > 05_vACC/${subj}_${type}_mvmw_vACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_vACC+tlrc > 05_vACC/${subj}_${type}_mvfw_vACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_vACC+tlrc > 05_vACC/${subj}_${type}_mvnw_vACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_dmFG+tlrc > 06_dmFG/${subj}_${type}_fvfw_dmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_dmFG+tlrc > 06_dmFG/${subj}_${type}_fvmw_dmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_dmFG+tlrc > 06_dmFG/${subj}_${type}_fvnw_dmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_dmFG+tlrc > 06_dmFG/${subj}_${type}_mvmw_dmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_dmFG+tlrc > 06_dmFG/${subj}_${type}_mvfw_dmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_dmFG+tlrc > 06_dmFG/${subj}_${type}_mvnw_dmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_vmFG+tlrc > 07_vmFG/${subj}_${type}_fvfw_vmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_vmFG+tlrc > 07_vmFG/${subj}_${type}_fvmw_vmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_vmFG+tlrc > 07_vmFG/${subj}_${type}_fvnw_vmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_vmFG+tlrc > 07_vmFG/${subj}_${type}_mvmw_vmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_vmFG+tlrc > 07_vmFG/${subj}_${type}_mvfw_vmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_vmFG+tlrc > 07_vmFG/${subj}_${type}_mvnw_vmFG.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvfw_mACC+tlrc > 08_mACC/${subj}_${type}_fvfw_mACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvmw_mACC+tlrc > 08_mACC/${subj}_${type}_fvmw_mACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_fvnw_mACC+tlrc > 08_mACC/${subj}_${type}_fvnw_mACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvmw_mACC+tlrc > 08_mACC/${subj}_${type}_mvmw_mACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvfw_mACC+tlrc > 08_mACC/${subj}_${type}_mvfw_mACC.txt
3dclust -1tindex 8 -1dindex 8 0 0 ${subj}_${type}_mvnw_mACC+tlrc > 08_mACC/${subj}_${type}_mvnw_mACC.txt