. $PROFILE/${1}_profile.sh
####################################################################################################
cd ${BEHAV_dir}
####################################################################################################
# Written by Dianne Patterson 5/11/2011
# Modified by Kyle Almryde 1/21/2012
# Thanks to Tom Hicks and Kyle Almryde for suggestions and troubleshooting
# Buttons 1 and 2 are equivalent (and what the subject should press if s/he thinks the test is a 
# nonword). Buttons 3 and 4 are equivalent (and what the subject should press if s/he thinks the 
# test is a true word)
####################################################################################################
echo "-------------------------------- examine.sh ----------------------------------"
echo "This examines the results from text originating in an eprime file generated by "
echo "the ${1} imaging experiment. It will match resposes, average results, then link"
echo "various items from the Test-Phase to the corresponding Study-Phase"
echo "-------------------------------- ${subrun} --------------------------------"
echo ""
####################################################################################################
# Pass the contents of Report.${subrun}.txt to awk
####################################################################################################

cat Report.${subrun}.txt 

if [ "${run}" = "TP1" ] 
#truepos=CA falsepos=IA trueneg=CR falsenega=IR 
#"Old = 1" CA
#"Old = 0" IR
#"New = 1" CR
#"New = 0" IA
