#!/usr/bin/env tcsh
echo "Command line conforms to following: ./ROIspheres Subject# Run v/w"
echo "./ROIspheres S23 voice v"
# execute via : tcsh -x S#-run-script |& tee output.S#-run-script

# --------------------------------------------------
# script setup



set images_home = /Volumes/Data/Stroop/ROIs

echo "Count Down Begins"

if ( $#argv > 0 ) then
    set subj = $argv[1]
else
# specify subject = ${subj}
set subj = $1

endif

echo "Assigning Variables"

#set run = voice/word
set run = $2

#set base = 42
set type = $3


3dcalc -a Masks/leftBA13_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_lBA13
3dcalc -a Masks/leftBA13_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_lBA13
3dcalc -a Masks/leftBA13_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_lBA13
3dcalc -a Masks/leftBA13_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_lBA13
3dcalc -a Masks/leftBA13_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_lBA13
3dcalc -a Masks/leftBA13_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_lBA13
3dcalc -a Masks/rightBA13_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_rBA13
3dcalc -a Masks/rightBA13_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_rBA13
3dcalc -a Masks/rightBA13_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_rBA13
3dcalc -a Masks/rightBA13_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_rBA13
3dcalc -a Masks/rightBA13_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_rBA13
3dcalc -a Masks/rightBA13_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_rBA13
3dcalc -a Masks/leftBA44_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_lBA44
3dcalc -a Masks/leftBA44_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_lBA44
3dcalc -a Masks/leftBA44_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_lBA44
3dcalc -a Masks/leftBA44_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_lBA44
3dcalc -a Masks/leftBA44_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_lBA44
3dcalc -a Masks/leftBA44_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_lBA44
3dcalc -a Masks/rightBA44_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_rBA44
3dcalc -a Masks/rightBA44_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_rBA44
3dcalc -a Masks/rightBA44_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_rBA44
3dcalc -a Masks/rightBA44_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_rBA44
3dcalc -a Masks/rightBA44_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_rBA44
3dcalc -a Masks/rightBA44_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_rBA44
3dcalc -a Masks/leftBA45_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_lBA45
3dcalc -a Masks/leftBA45_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_lBA45
3dcalc -a Masks/leftBA45_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_lBA45
3dcalc -a Masks/leftBA45_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_lBA45
3dcalc -a Masks/leftBA45_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_lBA45
3dcalc -a Masks/leftBA45_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_lBA45
3dcalc -a Masks/rightBA45_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_rBA45
3dcalc -a Masks/rightBA45_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_rBA45
3dcalc -a Masks/rightBA45_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_rBA45
3dcalc -a Masks/rightBA45_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_rBA45
3dcalc -a Masks/rightBA45_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_rBA45
3dcalc -a Masks/rightBA45_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_rBA45
3dcalc -a Masks/dACC_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_dACC
3dcalc -a Masks/dACC_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_dACC
3dcalc -a Masks/dACC_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_dACC
3dcalc -a Masks/dACC_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_dACC
3dcalc -a Masks/dACC_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_dACC
3dcalc -a Masks/dACC_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_dACC
3dcalc -a Masks/dmFG_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_dmFG
3dcalc -a Masks/dmFG_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_dmFG
3dcalc -a Masks/dmFG_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_dmFG
3dcalc -a Masks/dmFG_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_dmFG
3dcalc -a Masks/dmFG_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_dmFG
3dcalc -a Masks/dmFG_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_dmFG
3dcalc -a Masks/vACC_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_vACC
3dcalc -a Masks/vACC_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_vACC
3dcalc -a Masks/vACC_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_vACC
3dcalc -a Masks/vACC_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_vACC
3dcalc -a Masks/vACC_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_vACC
3dcalc -a Masks/vACC_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_vACC
3dcalc -a Masks/vmFG_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_vmFG
3dcalc -a Masks/vmFG_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_vmFG
3dcalc -a Masks/vmFG_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_vmFG
3dcalc -a Masks/vmFG_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_vmFG
3dcalc -a Masks/vmFG_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_vmFG
3dcalc -a Masks/vmFG_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_vmFG
3dcalc -a Masks/mACC_sphere10+tlrc -b Data/${subj}_${run}_fvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvfw_mACC
3dcalc -a Masks/mACC_sphere10+tlrc -b Data/${subj}_${run}_fvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvmw_mACC
3dcalc -a Masks/mACC_sphere10+tlrc -b Data/${subj}_${run}_fvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_fvnw_mACC
3dcalc -a Masks/mACC_sphere10+tlrc -b Data/${subj}_${run}_mvmw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvmw_mACC
3dcalc -a Masks/mACC_sphere10+tlrc -b Data/${subj}_${run}_mvfw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvfw_mACC
3dcalc -a Masks/mACC_sphere10+tlrc -b Data/${subj}_${run}_mvnw_norm_irf+tlrc -expr '(a*b)' -prefix DataSpheres/${subj}_${type}_mvnw_mACC
