dset = [(1,'L','Cerebellum-vermis',None,True,None),
        (1,'R','Cerebellum-VI',None,True,True),
        (1,'L','Cingulate-posterior',None,None,True),
        (1,'R','Cingulate-posterior',None,None,True),
        (1,'R','IFG-pars opercularis',None,None,True),
        (1,'R','IFG-pars triangularis',None,None,True),
        (1,'R','Lingual Gyrus',None,None,True),
        (1,'R','LOC',None,True,None),
        (1,'R','MTG',True,True,None),
        (1,'L','PostCG-dorsolateral',None,None,True),
        (1,'L','PreCG-dorsolateral 1',None,True,True),
        (1,'L','SFG-dorsal/paracingulate',None,True,None),
        (1,'R','SFG-dorsal/paracingulate',None,True,None),
        (1,'L','STG',True,True,True),
        (1,'R','STG',None,None,True),
        (1,'L','Thalamus',None,True,None),
        (1,'R','Thalamus',None,True,True),
        (2,'R','Angular Gyrus',None,True,None),
        (2,'R','Caudate-head',True,None,None),
        (2,'R','Caudate-head 1',True,None,None),
        (2,'R','Cingulate-anterior',None,None,True),
        (2,'R','Insula-anterior',None,None,True),
        (2,'R','Insula-middle',None,None,True),
        (2,'R','LOC-dorsolateral',None,True,None),
        (2,'L','LOC-inferior',None,True,True),
        (2,'R','LOC-inferior',True,None,None),
        (2,'L','MTG-anterior',True,None,None),
        (2,'R','MTG-anterior',True,None,None),
        (2,'L','MTG-posterior',True,None,None),
        (2,'R','MTG-posterior',True,None,None),
        (2,'R','PreCG-lateral',True,True,None),
        (2,'L','Precuneus-inferior',None,None,True),
        (2,'R','Precuneus-inferior',True,None,True),
        (2,'L','Precuneus-superior',True,None,None),
        (2,'L','SMG',None,None,True),
        (2,'L','SMG 1',None,True,None),
        (2,'R','STG-posterior',None,None,True),
        (2,'L','Subcallosal gray',None,None,True),
        (3,'L','Angular Gyrus',True,True,True),
        (3,'L','Anterior Insula',None,None,True),
        (3,'L','Brainstem-midbrain',None,None,True),
        (3,'R','Brainstem-midbrain',None,None,True),
        (3,'R','Cingulate-posterior inferior',None,None,True),
        (3,'R','Fusiform-occipital division',None,True,None),
        (3,'L','IFG-pars opercularis',True,True,None),
        (3,'R','IFG-pars opercularis 1',True,None,None),
        (3,'R','IFG-pars orbitalis',None,True,True),
        (3,'R','Insula-anterior 1',None,None,True),
        (3,'R','Insula-middle 1',True,True,None),
        (3,'R','Lingual Gyrus 1',None,True,None),
        (3,'R','LOC-dorsolateral 1',None,None,True),
        (3,'R','LOC-superior',True,None,True),
        (3,'L','MFG--anterior',None,True,None),
        (3,'L','MFG-dorsolateral',None,None,True),
        (3,'L','MFG-ventral',None,None,True),
        (3,'L','MTG',True,True,True),
        (3,'L','MTG-posterior 1',None,True,None),
        (3,'L','Orbital Gyrus',None,True,None),
        (3,'L','PreCG-Inferior',None,True,None),
        (3,'R','Precuneus-inferior 1',None,None,True),
        (3,'L','Precuneus-superior 1',True,None,True),
        (3,'L','SFG-dorsomedial',True,None,True),
        (3,'R','SFG-dorsomedial',True,True,True),
        (3,'L','SFG-frontal pole',None,None,True),
        (3,'L','SFG-ventromedial',None,None,True),
        (3,'R','SFG-ventromedial',None,True,True),
        (3,'L','SMG-inferior',None,True,None),
        (3,'R','STG-temporal pole',None,True,None),
        (3,'L','Thalamus 1',None,True,True),
        (3,'R','Thalamus 1',None,None,True),
        (4,'L','Amygdala',None,None,True),
        (4,'L','Angular Gyrus 1',True,None,True),
        (4,'R','Angular Gyrus 1',True,True,True),
        (4,'L','Brainstem-midbrain 1',True,None,None),
        (4,'R','cerebellum-Crus II',None,None,True),
        (4,'L','Cerebellum-V',True,None,None),
        (4,'R','Cerebellum-V',None,True,None),
        (4,'R','Cerebellum-Vermis',True,None,None),
        (4,'R','Cerebellum-VI  1',True,None,None),
        (4,'L','Cingulate-anterior',None,True,None),
        (4,'R','Cingulate-anterior 1',None,True,None),
        (4,'L','Cingulate-posterior 1',None,None,True),
        (4,'L','Fusiform-temporal division',True,None,None),
        (4,'L','Globus Palidus',None,None,True),
        (4,'L','IFG-pars opercularis 1',True,True,None),
        (4,'L','IFG-pars orbitalis',None,None,True),
        (4,'R','Lingual Gyrus 2',True,None,True),
        (4,'R','Lingual/Cerebellum',True,True,True),
        (4,'L','MFG-dorsolateral 1',None,True,None),
        (4,'L','MFG-frontal pole',True,None,None),
        (4,'L','MTG 1',True,True,True),
        (4,'R','MTG 1',None,None,True),
        (4,'L','Orbital gyrus',True,True,True),
        (4,'L','Parahippocampal gyrus',True,None,None),
        (4,'L','Parahippocampal gyrus 1',None,None,True),
        (4,'R','Parietal operculum',True,True,True),
        (4,'R','PostCG-dorsal',True,True,True),
        (4,'R','PreCG-dorsal',None,True,None),
        (4,'L','Precuneus-inferior 1',None,True,None),
        (4,'R','Precuneus-inferior 2',True,None,None),
        (4,'L','Precuneus-middle',True,None,None),
        (4,'L','Putamen',True,None,None),
        (4,'L','SFG-dorsomedial 1',True,None,None),
        (4,'R','SFG-dorsomedial 1',True,True,True),
        (4,'L','SFG-dorsomedial 2',None,True,None),
        (4,'L','SFG-dosolateral',None,None,True),
        (4,'L','SFG-frontal pole 1',True,None,True),
        (4,'R','SFG-ventromedial 1',None,None,True),
        (4,'R','STG 1',True,True,None),
        (4,'L','Thalamus 1',True,None,None),
        (5,'R','Angular Gyrus 2',None,None,True),
        (5,'L','Cerebellum-crus I',None,True,None),
        (5,'R','Cerebellum-crus I',True,None,None),
        (5,'L','Cingulate-anterior 1',True,True,True),
        (5,'R','Cingulate-anterior 2',None,None,True),
        (5,'L','Cingulate-posterior 2',True,True,True),
        (5,'L','Cingulate-posterior inferior',None,None,True),
        (5,'R','Cingulate-posterior inferior 1',None,True,None),
        (5,'R','Cingulate-posterior 1',True,None,None),
        (5,'L','Cuneate gyrus',None,True,True),
        (5,'R','Cuneate gyrus',None,True,True),
        (5,'L','Fusiform-Temporal division',None,None,True),
        (5,'R','IFG-pars opercularis 2',None,None,True),
        (5,'R','IFG-pars triangularis 1',True,True,None),
        (5,'R','ITG',True,True,True),
        (5,'L','ITG-posterior',True,True,None),
        (5,'L','LOC-superior',None,True,True),
        (5,'R','LOC-superior 1',True,True,None),
        (5,'L','MFG-dorsolateral',None,None,True),
        (5,'L','PreCG-dorsolateral',True,True,True),
        (5,'L','SFG--ventromedial',True,None,None),
        (5,'L','SFG-frontal pole 2',None,True,True),
        (5,'R','SFG-frontal pole',True,True,True),
        (5,'L','SMG',True,None,None),
        (5,'R','SMG',True,True,None),
        (5,'L','SPL',None,True,None),
        (5,'R','STG-temporal pole 1',None,True,True)]
