#!/usr/bin/env csh
echo "Command line conforms in the following way"
echo "./Correlation Subject Run X Y Z seed congruency"
# execute via : tcsh -x S#-run-script |& tee output.S#-run-script
# --------------------------------------------------
# script setup
#Establish loops
foreach run (voice word)
foreach seed (vACC dACC)
foreach con (cong inc)
						echo " S{$subj} $run $seed $con"
set subj 20
						echo "S{$subj}"
						echo "S{$subj}"
end
end
end
end
#Establish localtion variables
set Home = /Volumes/Data/Stroop
set subj_dir = $images_home/${subj}
set results = $subj_dir/${subj}_${run}_${seed}_Corr
set group = $images_home/AnovaData/Correlation/${run}
# assign anchor directory name


# assign output directory name


#assign group directory name


# verify that the results directory does not yet exist
if ( -d $results_dir ) then 
    echo output dir "${subj}_${run}_Process" already exists
   
   exit

  endif

echo "Enter ${subj} directory"
# change directories to subject directory
cd $subj_dir

echo "Making $results_dir directory"
# create results and group analysis directory
mkdir $results_dir

echo "Enter $results_dir directory"
#change directory to results
cd $results_dir

echo "Making Data directory"
#create data storage directory
mkdir $results_dir/Step.0

echo "Anatomical"
cp $subj_dir/struct/Tal/*spgr+tlrc* $results_dir/Step.0
echo "${run} Norm"
cp $subj_dir/${subj}_${run}_PreProcess/06_Norm/*mean* $results_dir/Step.0
echo "${run}_${congruency}.txt"
cp $images_home/${run}_${congruency}.txt $results_dir/Step.0 

#-------------------------------------------------------
# Warp datasets to Talairach space
echo "warping norms to standard space"

adwarp -apar ${subj}_spgr+tlrc -dpar ${subj}_${run}_mean+orig -dxyz 3

mkdir $results_dir/Step.1
#-------------------------------------------------------
#3dMaskdump 
echo "Step 1"

3dmaskdump -noijk -dbox ${x} ${y} ${z} ${subj}_${run}_mean+tlrc > ${subj}_${run}_${seed}.1D
1dplot -one ${subj}_${run}_${seed}.1D

mkdir $results_dir/Step.2
#-------------------------------------------------------
#Detrending
echo "Step 2"

3dDetrend -polort A -prefix ${subj}_${run}_${seed}.1D
1dplot -one   ${subj}_${run}_${seed}_Detrend.1D
1dtranspose ${subj}_${run}_${seed}_TimeScale.1D

mkdir $results_dir/Step.3
#-------------------------------------------------------
#Generating the impulse response function
#I am going to figure out what the Deconvolve version should be  -Kyle
echo "Step 3"

waver -dt 3.5 -GAM -inline 1@1 > GammaHR.1D
1dplot GammaHR.1D
#I suspect we are overwritting GammaHR.1D when we should be creating *_neur.1d
3dTfitter -RHS ${subj}_${run}_${seed}_Neur 012 0
1dplot GammaHR.1D

mkdir $results_dir/Step.4
#-------------------------------------------------------
#1dEval and waver
echo "Step 4"

1deval -a ${subj}_${run}_${seed}_Inter_neu.1D
waver -GAM -peak 1 -TR 3.5 -input ${subj}_${run}_${seed}_Inter_ts.1D
1dplot ${subj}_${run}_${seed}_Inter_ts.1D

mkdir $results_dir/Step.5
#-------------------------------------------------------
echo "Skipping Step 5"



mkdir $results_dir/Step.6
#-------------------------------------------------------
echo "Step 6"


3dDeconvolve -input ${subj}_${run}_mean+tlrc			\
-polort A 													\
-num_stimts 2 												\
-stim_file 1 ${subj}_${run}_${seed}_TimeScale.1D		\
-stim_label 1 ${subj}_${run}_${seed}_TimeScale		\
-stim_file 2 ${subj}_${run}_${seed}_Inter_ts.1D		\
-stim_label 2 ${subj}_${run}_${seed}_Inter_ts_con	\
-rout -bucket corr_${subj}_${run}_${seed}_Inter_ts_con

mkdir $results_dir/Step.7
#-------------------------------------------------------
#3dCalc
echo "Step 7"


3dcalc -a Corr_${subj}_${run}_${seed}_R 














