#!/usr/bin/env tcsh
# execute via : tcsh -x S#-run-script |& tee output.S#-run-script
# --------------------------------------------------
# script setup
echo "./MeanMasking"
set images_home = /Volumes/Data/MRI-AttnMem/Anova
foreach task (ff mf nf)
foreach gam (1 2 3 4 5 6 7)
foreach mask (AI CAU CER CIN IFG IFG2 IFG3 MFG MFG2 MTG SFG SMG SOG STG THA) 
set results_dir = $images_home/${task}/roi
# --------------------------------------------------
# Apply Mask to Data
echo "masking ${mask}_GAM${gam}_${task}"
3dcalc -a Masks/${mask}+tlrc -b ${task}/mean_GAM${gam}_${task}_0.05+tlrc -expr '(a*b)' -prefix $results_dir/${mask}_GAM${gam}_${task}+tlrc
# --------------------------------------------------
# Clusterize data
echo "Clusterize!"
3dclust -1noneg 1 10 $results_dir/${mask}_GAM${gam}_${task}+tlrc'[0]' > $results_dir/${mask}_GAM${gam}_${task}.txt
echo "Print it"
cat $results_dir/${mask}_GAM${gam}_${task}.txt | colrm 10 73 | sed '/^#/d' | tr -s '[:space:]' | awk -v OFS='\t' '$1=$1' | head -2 > $results_dir/${mask}_GAM${gam}_${task}.txt
echo "where am i?"
whereami -tab -atlas TT_Daemon -coord_file $results_dir/${mask}_GAM${gam}_${task}.txt'[4,5,6]' | sed -n '/TT_Daemon/p' | awk -v OFS='\t' '$1=$1 {print $2,$4,$5,$6}'| head -4 > $results_dir/${mask}_GAM${gam}_${task}_whereami.txt
# --------------------------------------------------
end
end
end
